CREATE TABLE users (
                      "id" bigint generated by default as identity not null primary key ,
                      "uuid" uuid default uuid_generate_v4() unique not null,
                      "login" varchar(255) unique not null,
                      "lastname" varchar(255) not null,
                      "firstname" varchar(255) not null,
                      "user_role" varchar(13) not null CHECK (user_role IN('ADMINISTRATOR', 'MANAGER', 'EMPLOYEE')),
                      "password" varchar(255) not null,
                      "email" varchar(255) not null,
                      "salary_per_hour" integer not null
)